#:schema node_modules/wrangler/config-schema.json
name = "bsa"
main = ".open-next/worker.js"
compatibility_date = "2025-03-10"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "business-simulation-db-prod"
database_id = "5b58457b-91d9-452e-b39a-7abf0ca8b2ce"
