#:schema node_modules/wrangler/config-schema.json
name = "bsa"
main = ".open-next/worker.js"
compatibility_date = "2025-03-10"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "businesssimulation-db"
database_id = "9d1b070f-fb7d-4cb2-ba26-f82629e99b59"