import type { Metadata } from 'next'
import './globals.css'
import { Inter } from "next/font/google";
import { Toaster } from '@/components/ui/sonner';
import { AuthProvider } from '@/lib/auth-context';
import { ThemeProvider } from '@/components/theme-provider';

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: 'Business Simulation',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className="light">
      <body className={`${inter.variable} ${inter.variable} antialiased`}><AuthProvider>{children}</AuthProvider><Toaster position="top-center"/></body>
    </html>
  )
}
